# 一、ndarray
## 1、ndarray的特性
### 多维性

In [3]:
import numpy as np

In [4]:
arr = np.array(5) # 创建0维的ndarray数组
print(arr)
print('arr的维度：',arr.ndim)

5
arr的维度： 0


In [5]:
arr = np.array([1,2,3]) # 创建1维的ndarray数组
print(arr)
print('arr的维度：',arr.ndim)

[1 2 3]
arr的维度： 1


In [6]:
arr = np.array([[1,2,3],[4,5,6]]) # 创建2维的ndarray数组
print(arr)
print('arr的维度：',arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度： 2


### 同质性


In [7]:
arr = np.array([1,'hello']) # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

['1' 'hello']


In [8]:
arr = np.array([1,2.5])
print(arr)

[1.  2.5]


## 2、ndarray的属性

In [9]:
arr = np.array(1)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.T)

1
()
1
int64
8
1


In [10]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.T)

[1 2 3 4 5]
(5,)
5
int64
8
[1 2 3 4 5]


In [11]:
arr = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.T)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
10
int64
8
[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]


## 3、ndarray的创建

In [14]:
# 基础的创建方法
list1 = [1,2,3]
arr = np.array(list1,dtype=np.float64)
print(arr)
print(arr.ndim)

[1. 2. 3.]
1


In [16]:
# copy
arr1 = np.copy(arr) # 元素跟原始的数组相同，但是不是一个数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1. 2. 3.]
[8. 2. 3.]
[1. 2. 3.]


In [17]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2,3),dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [19]:
arr = np.zeros((200,),dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [27]:
# 全1
arr = np.ones((5,8),dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [28]:
# 未初始化
arr = np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
arr = np.empty((4,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [30]:
arr = np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [34]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [36]:
# 等差数列
arr = np.arange(1,50,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [37]:
# 等间隔数列
arr = np.linspace(0,100,5)
print(arr)

[  0.  25.  50.  75. 100.]


In [39]:
arr = np.linspace(0,100,5,dtype=int)
print(arr)
arr = np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [51]:
# 对数间隔数列
arr = np.logspace(0,4,3,base=2)
print(arr)

[ 1.  4. 16.]


In [48]:
arr = np.linspace(0,4,3)
print(arr)

[0. 2. 4.]


In [54]:
arr = np.logspace(0,4,3,dtype=int)
print(arr)

[    1   100 10000]


In [57]:
# 特殊矩阵
# 单位矩阵，主对角线上的数字为1，其他数字为0
arr = np.eye(5,5,dtype=int)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [58]:
# 对角矩阵，主对角线上非0的0，其他位置为0
arr = np.diag([4,5,6,7])
print(arr)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


In [63]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

[[0.57545469 0.31155731 0.80122852]
 [0.1085039  0.54063122 0.91364353]]


In [68]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[4.48329373 5.01687861 3.78802128]
 [3.29392282 3.45736821 4.07622762]]


In [88]:
# 生成指定区间的随机整数
arr = np.random.randint(1,11,(2,3))
print(arr)

[[4 4 5]
 [6 7 3]]


In [94]:
# 生成随机数列（正太分布）
arr = np.random.randn(2,3)
print(arr)
arr = np.random.random(3)
print(arr)

[[-0.14539056 -1.08806522  0.06027999]
 [ 0.30256103 -1.42297368  0.29682605]]
[0.59460639 0.72471907 0.79677609]


In [166]:
# 设置随机种子
np.random.seed(0)
arr = np.random.randint(1,10,(2,5))
print(arr)
arr = np.array([1,2,3],dtype='i8')
print(arr)

[[6 1 4 4 8]
 [4 6 3 5 8]]
[1 2 3]


### 4、ndarray的数据类型
### 布尔类型bool
### 整数类型int uint
### 浮点数float
### 复数complex

In [167]:
arr = np.array([1,2,3],dtype=np.int8)
print(arr)

[1 2 3]


### 5、索引与切片

In [168]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20) # 生成1-100的随机整数20个
print(arr)

[71 89 89 13 59 66 40 88 47 89 82 38 26 78 73 10 21 81 70 80]


In [172]:
print(arr[10]) # 获取索引为10位置的数据
print(arr[:]) # 获取全部数据
print(arr[2:5]) # 左包右不包
print(slice(2,15,3)) # start,end,step
print(arr[slice(2,15,3)])
print(arr[(arr > 10) & (arr < 70)]) # 布尔索引
print((arr > 10) & (arr < 70))

82
[71 89 89 13 59 66 40 88 47 89 82 38 26 78 73 10 21 81 70 80]
[89 13 59]
slice(2, 15, 3)
[89 66 47 38 73]
[13 59 66 40 47 38 26 21]
[False False False  True  True  True  True False  True False False  True
  True False False False  True False False False]


In [173]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)

[[48 65 83 89 50 30 20 20]
 [15 40 33 66 10 58 33 32]
 [75 24 36 76 56 29 35  1]
 [ 1 37 54  6 39 18 80  5]]


In [177]:
print(arr[1,3]) # 索引
print(arr[1,2:5])
print(arr[2][arr[2] > 50])
print(arr[:,3])

66
[33 66 10]
[75 76 56]
[89 66 76  6]


### 5、ndarray的运算

In [178]:
# 算数运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [181]:
c = [1,2,3]
d = [4,5,6]
print(c+d)
for i in range(len(c)):
    d[i] = c[i] * d[i]
print(d)

[1, 2, 3, 4, 5, 6]
[4, 10, 18]


In [184]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [186]:
# 数组与标量之间的算术运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a + 3)
print(a - 3)
print(a * 3)
print(a / 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [188]:
# 广播机制：1、获取形状 2、是否可广播
# 同一维度：相同、1
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a + b)
print(b - a)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


In [189]:
a = np.array([1,2,3]) #1*3
b = np.array([4,5])  #1*2
print(b - a )

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [190]:
# 矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a @ b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


### 2.3、numpy中常用的函数
### 1、基本数学函数

In [196]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9],dtype=float))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [197]:
# 计算指数
print(np.exp(1))

2.718281828459045


In [198]:
# 计算自然对数
print(np.log(2.718))

0.999896315728952


In [201]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))
print(np.cos(np.pi/3))

1.0
0.5000000000000001


In [202]:
# 计算绝对值
arr = np.array([1,2,3,-1,-4])
print(np.abs(arr))

[1 2 3 1 4]


In [203]:
# 计算a的b次幂
print(np.power(arr,2))

[ 1  4  9  1 16]


In [204]:
# 四舍五入
print(np.round([3.2,3.5,3.6,6,5.6]))

[3. 4. 4. 6. 6.]


In [205]:
# 向上取整，向下取整
arr = np.array([3.2,3.5,3.6,6,5.6])
print(np.ceil(arr))
print(np.floor(arr))

[4. 4. 4. 6. 6.]
[3. 3. 3. 6. 5.]


In [206]:
# 检测缺失值
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

### 2、统计函数
### 求和、计算平均值、计算中位数、标准差、方差
### 查找最大值、最小值
### 计算分位数、累积和、累积差

In [207]:
arr = np.random.randint(1,100,8)
print(arr)

[43 59 32  2 66 42 58 36]


In [208]:
# 求和
print(np.sum(arr))

338


In [209]:
# 计算平均值
print(np.mean(arr))

42.25


In [212]:
# 计算中位数
# 奇数：排序后中间的数值
# 偶数：中间的两个数的平均值
print(np.median([4,1,2]))
print(np.median([4,1,2,3,4,5]))

2.0
3.5


In [214]:
# 计算标准差、方差
arr1 = np.array([1,2,3,4,5,2,2,3,1,1])
arr2 = np.array([1,0,3,1,5,9,2,3,6,1])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))

2.4
3.1
1.6400000000000001
7.089999999999999


In [216]:
# 计算最大值和最小值
print(arr)
print(np.max(arr),np.argmax(arr))  # argmax 返回该最大值的索引
print(np.min(arr),np.argmin(arr)) # argmin 返回该最小值的索引

[43 59 32  2 66 42 58 36]
66 4
2 3


In [222]:
# 分位数
# 中位数
print(np.median([1,2,4]))
print(np.median([4,1,2,3,4,5]))
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)
print(np.median(arr))
print(np.percentile(arr,80))

2.0
3.5
[44 47 64 67]
55.5
65.2


In [225]:
# 累积和、累积积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


In [233]:
# 创建嵌套JSON结构的数据
import json
products = {
    "products": [
        {
            "id": f"P{i}",
            "name": f"Product {i}",
            "category": np.random.choice(["Electronics", "Clothing", "Home", "Food"]),
            "price": round(np.random.uniform(5, 200), 2),
            "in_stock": np.random.choice([True, False]),
            "specs": {
                "weight": round(np.random.uniform(0.1, 5), 2),
                "dimensions": {
                    "length": np.random.randint(5, 50),
                    "width": np.random.randint(5, 30),
                    "height": np.random.randint(5, 20)
                }
            }
        } for i in range(1, 21)
    ]
}

def json_serializer(obj):
    if isinstance(obj, np.bool_):
        return bool(obj)
    elif isinstance(obj, (np.integer, np.int32, np.int64)):
        return int(obj)
    elif isinstance(obj, (np.floating, np.float32, np.float64)):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    raise TypeError(f"Type {type(obj)} not serializable")

with open('data/products.json', 'w') as f:
    print(type(products))
    json.dump(products, f, indent=2, default=json_serializer)

<class 'dict'>
